config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.erb
<% provide(:title, "About") %>
<h1>Eckelmeyer.com</h1>

<h2>Thanks for visiting Eckelmeyer.com!</h2>

<p>You may be wondering, "Why does it say, 'eckelmeyer.herokuapp.com' and not 'eckelmeyer.com' in my browser's address bar?</p>
<p>Good question! Heroku.com provides web hosting solutions for a variety of platforms for a variety of needs. This web application runs on Ruby on Rails (which Heroku makes it easy to get up and running.) Heroku also provides very basic (i.e. Free!) hosting, which includes very important security measures. The passing of information between this website and your PC, laptop, phone, etc., is secured by Heroku's SSL (You may have noticed the green lock in the address bar or that the URL starts with 'https'.) </p>
<p>Now, I could have Heroku host my website and I could use the 'eckelmeyer.com' domain with them, but then I have to go from a free account to buying a SSL certificate and a more costly hosting subscription. Since this is more a hobby website than a site intended to make money, I rather go the cheaper route - at least for now.</p>

<h2>About... Keith</h2>
<p>I'm a dad first and foremost. My professional experience can be found on <a href="https://www.linkedin.com/in/keith-a-eckelmeyer-mba-8231032a">LinkedIn</a>. I'm very interesting in building my Ruby on Rails experience, so if you are a small business or non-profit, please email me at <a href="mailto:keith.eckelmeyer@gmail.com">keith.eckelmeyer@gmail.com</a> and I can get you a Rails website up and running in little time for little or no money - just your reference on my resume.</p>

<h2>About... the website</h2>
<p>As stated above, this site is hosted by <a href="www.heroku.com">Heroku</a> and is built using the Ruby on Rails platform. The user account and associated account activation and password reset functionality is provided by <a href= "http://www.railstutorial.org/" > Ruby on Rails Tutorial </a> by Michael Hartl. It's a great tutorial and best read and performed several times to absorb the wealth of knowledge. If you are new to Ruby on Rails, I would recommend <a href="http://www.codeschool.com">Code School</a> (for the Zombie Rails tutorials) and <a href="http://www.codeacademy.com">Code Academy</a> (for the Ruby tutorials) first, or perhaps after the first few chapters. Michael gets into some advanced stuff, and while he does a great job explaining, it helps to have some beginner basics under your belt first. Even then, I find the more I repeat the Ruby on Rails tutorial, the more I get out of it.</p>
<p>Future plans for my site include the following:
  <ul>
    <li>A blog (which I'm not very good at keeping up with.)</li>
    <li>A list of learning resources I have used for my personal education.</li>
    <li>A database for ferret food, rating food types based on ingredients.</li>
    <li>Connecting to Facebook and Google+ for user account integration.</li>
    <li>Connecting and retrieving information from other websites via API.</li>
    <li>A hangman game.</li>
    <li>A movie trailer review system.</li>
    <li>A specifications database (proof of concept for a work project).</li>
    <li>And more (things that I have written down somewhere...)!</li>
  </ul>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  <ul>
    <li><a href="mailto:keith.eckelmeyer@gmail.com">Email</a></li>
    <li>BitBucket</li>
    <li>GitHub</li>
  </ul>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1> Help </h1>
<p><a href="mailto:keith.eckelmeyer@gmail.com">Email me!</a></p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Eckelmeyer.com</h1>
  <h2>This is the home page for Keith Eckelmeyer's Ruby on Rails applications.</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div>
  <small>
    Wait? Eckelmeyer.com? The address bar says "eckelmeyer.herokuapp.com"! See the <%= link_to "About", about_path %> page.
  </small>
</div>
<h1>
  <%= link_to image_tag("rails-logo.svg", size: "150", alt: "Rails logo") , 'http://rubyonrails.org/'%>
</h1>